"""create push subscriptions table"""

from alembic import op  # noqa: F401

revision = '87c4eabe55db'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # This was an autogenerated diff against a database that had a multi-tenant branch's tables
    # (tenant_id columns, user_branding, platform_settings) whose actual creation migrations were,
    # like 0013-0016 (see 0013_group_chats_new_message.py), never committed to this repo. On our
    # chain those objects never existed, so every drop_* call here targets something that isn't
    # there, and its two create_table calls (push_subscriptions, auction_comments) duplicate what
    # 0011 and 0012 already create. Nothing later in the chain or in the current models references
    # tenant_id/user_branding/platform_settings/users.slug, so there's nothing to preserve here.
    # Stubbed to a no-op, same as 0017.
    pass


def downgrade() -> None:
    pass
