"""create push subscriptions table"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '87c4eabe55db'
down_revision = '0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('auction_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_comments_auction_id'), 'auction_comments', ['auction_id'], unique=False)
    op.drop_table('platform_settings')
    op.drop_table('user_branding')
    op.drop_index(op.f('ix_auction_requests_seller_id'), table_name='auction_requests')
    op.drop_index(op.f('ix_auction_requests_status'), table_name='auction_requests')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_constraint(op.f('fk_campaigns_tenant_id'), 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'tenant_id')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_index(op.f('uq_categories_main_tenant_slug'), table_name='categories', postgresql_where='(parent_id IS NULL)')
    op.drop_index(op.f('uq_categories_sub_tenant_slug'), table_name='categories', postgresql_where='(parent_id IS NOT NULL)')
    op.create_index('uq_categories_main_slug', 'categories', ['slug'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_index('uq_categories_sub_slug', 'categories', ['parent_id', 'slug'], unique=True, postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_constraint(op.f('fk_categories_tenant_id'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'tenant_id')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_constraint(op.f('fk_leads_tenant_id'), 'leads', type_='foreignkey')
    op.drop_column('leads', 'tenant_id')
    op.drop_index(op.f('ix_properties_tenant_id'), table_name='properties')
    op.drop_constraint(op.f('fk_properties_tenant_id'), 'properties', type_='foreignkey')
    op.drop_column('properties', 'tenant_id')
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('fk_users_tenant_id'), 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_tenant_id'), 'users', 'users', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('properties', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_properties_tenant_id'), 'properties', 'users', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_properties_tenant_id'), 'properties', ['tenant_id'], unique=False)
    op.add_column('leads', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_leads_tenant_id'), 'leads', 'users', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.add_column('categories', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_categories_tenant_id'), 'categories', 'users', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_categories_sub_slug', table_name='categories', postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_index('uq_categories_main_slug', table_name='categories', postgresql_where=sa.text('parent_id IS NULL'))
    op.create_index(op.f('uq_categories_sub_tenant_slug'), 'categories', ['tenant_id', 'parent_id', 'slug'], unique=True, postgresql_where='(parent_id IS NOT NULL)')
    op.create_index(op.f('uq_categories_main_tenant_slug'), 'categories', ['tenant_id', 'slug'], unique=True, postgresql_where='(parent_id IS NULL)')
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.add_column('campaigns', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_campaigns_tenant_id'), 'campaigns', 'users', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auction_requests_status'), 'auction_requests', ['status'], unique=False)
    op.create_index(op.f('ix_auction_requests_seller_id'), 'auction_requests', ['seller_id'], unique=False)
    op.create_table('user_branding',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_branding_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_branding_pkey'))
    )
    op.create_table('platform_settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('platform_settings_updated_by_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('platform_settings_pkey'))
    )
    op.drop_index(op.f('ix_auction_comments_auction_id'), table_name='auction_comments')
    op.drop_table('auction_comments')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
